name:                anki-types
version:             0.1.0.0
github:              "githubuser/anki-types"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/anki-types#readme>

dependencies:
- base >= 4.7 && < 5
- text
- unordered-containers
- aeson
- req
- microlens
- microlens-th
  
default-extensions:
  - FlexibleInstances
  - FlexibleContexts
  - InstanceSigs
  - MultiParamTypeClasses
  - ConstraintKinds
  - LambdaCase
  - EmptyCase
  - TupleSections
  - BangPatterns
  - TypeApplications
  - StandaloneDeriving
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - NamedFieldPuns
  - DuplicateRecordFields
  - GeneralizedNewtypeDeriving
  - DataKinds
  - ConstraintKinds
  - TypeApplications
  - KindSignatures
  - StandaloneKindSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable 
  - GeneralizedNewtypeDeriving
  - GADTs
  - PolyKinds
  - ViewPatterns
  - PatternSynonyms
  - TypeFamilies
    
ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

tests:
  anki-types-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - anki-types